# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      # cloud function
      - name: Cloud Functions Deploy
        # You may pin to the exact commit or the version.
        # uses: google-github-actions/deploy-cloud-functions@7faa962492ec7b650406d15004fc19c6880f94d0
        uses: google-github-actions/deploy-cloud-functions@v0.1.2
        with:
          credentials: 0db4818ce0203a4662b5e9c61bdf89fd6e7f91ed
          # Name of the Cloud Function.
          name: cf-java-gha-test
          # Description for the Cloud Function.
          description: cf-java-gha-test
          # Project to deploy the function in.
          project_id: deft-effect-317609
          # Region to deploy the function in. Defaults to us-central1, if not specified.
          region: us-central1
          # Path to function deployment directory within the source repo.
          source_dir: src
          # List of key-value pairs to set as environment variables in the form KEY1=VALUE1,KEY2=VALUE2.
          #env_vars: # optional
          # Name of a function (as defined in source code) that will be executed. Defaults to the resource name suffix, if not specified. 
          #entry_point: # optional
          # Runtime to use for the function.
          runtime: java11
          # The VPC Access connector that the function can connect to.
          #vpc_connector: # optional
          # The email address of the IAM service account associated with the function at runtime.
          #service_account_email: # optional
          # The function execution timeout.
          #timeout: # optional
          # The maximum number of instances for the function.
          #max_instances: # optional
          # Specifies which action should trigger the function.
          event_trigger_type: providers/cloud.storage/eventTypes/object.finalize
          # Specifies which resource from eventTrigger is observed.
          # event_trigger_resource: projects/_/buckets/my-bucket/objects/*
          # The hostname of the service that should be observed.
          # event_trigger_service: # optional
