# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      # cloud function
      - id: Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          credentials: eyJ0eXBlIjoic2VydmljZV9hY2NvdW50IiwicHJvamVjdF9pZCI6ImRlZnQtZWZmZWN0LTMxNzYwOSIsInByaXZhdGVfa2V5X2lkIjoiMGRiNDgxOGNlMDIwM2E0NjYyYjVlOWM2MWJkZjg5ZmQ2ZTdmOTFlZCIsInByaXZhdGVfa2V5IjoiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUUMvZ01TRHd4cTc2bEU1XG51SDN0Ynh1bFFXMWxNaUZZRWlReml0MUszSkZmSjFyUm9oK1Nlc0tJS04zbnhvUnJ6UmFMcmw3THkrYi92WTRxXG5rYitaaXByNlUvK1dsT1I1MzlUdlNFaDc3SjlSWWxQc3VxUzRkbTZ1YnBVbjRBK29qQkJRbUtmQ1VUSEtxNWJzXG4rOHYxU0xjN2pzVC9ZZ1d1b2ZpMkkyUkR0VTd0TGtKYmlKRVpLZXNrOSsvYjdKWDBKTjVCYUN4dU50Q3ZpOEJSXG54TmprZ0svUlQ4Mm5KMmVUU1RxWFlrM0twQ05EcXB2MmxTRTZhT0o0WStZTTdoTm1aS2ZweWZ2VlhLeWpvVExwXG5OYVVBOFNscmgvaXV6b0ZRblUyNWdtbmo0YWZzTXVEUERnV2Fxd2JrU1pMSTR6VTI4YklnZzdPcFpNalJBa2tQXG5uTm5tR0dYakFnTUJBQUVDZ2dFQUN3VkNpZUNpKzdoMjF5OEdWREVtTXFMcXhEMlh6S1V5bnlLNUxITTRESFZMXG4xUytTeUkrMi9UWDQyenRCNktCRFVXT0dBZzFvYkVSQTE3Tk9odXdDa2pCZVQ1Q2UrMktGc3dXQ1lsdFNLZEZTXG5TaGZObmUzMjNhUHdnbnh5K2p5aFBib2pRVndCMVF0OTRvSjFFTmNQOEdYOWNVTDNWNzdyZkxQWnM4bk4wbmxTXG4wYWtjdUVVUng4RlNXbmpVRW5rOE9SRmRVT0FDYlZiZndRVkFLKytmVTFXWVR2K3VUcDJJWndySnJhM1FFTFBKXG5nU0JtL3hac0N4bU9mQ1hDM1AxT2lnbjRqM0pzOFYvclh1K0pOTExQZm9KUm9hek5YRXhNemcvUTl0NU5HV0VWXG55dHE1RkVaaHN4T1BFNEx2SEFhcGpNR0thbG5XZU9PTHh0T2Y3RjZFY1FLQmdRRDljMklOdzhFNUJWdFJNcEQ1XG5iNGN1akN6SFQzZ2tpY05yWEdIb1k0cW4yTUhveTBDbElraUhreHhqTDRLcllIZFYySlAzb0JDb3dSb2JXNk52XG5Pek1mRWlGN1FoYjB3VUs5WmczMVJTUjFBUFhOTDkvYVFJbERENDBnRG9hWTlyY1ppWlpzQmJMNWNsYnBJa0RrXG5qclB6anM4MnZ5Q09JR1lVZXJhM3ROektNd0tCZ1FEQmJkK3c0eTk0dnJXeGNaV0t0ckJPTG12ZUQ4RjRCeVk3XG42ejBNLytmdHhleE5TRHdQa0dndFpRMnk2aXk0S3A0UXEyWlRXU2RnOHBzOU1DTk9PQUxEMXFPdEc4WmpPSHNlXG40R1FmTEN0eTI5OElHUjdYM0NRZkkycXVSNU5Vd2prMmZpVFQ3RHBuamlyYTIzbmFFL0hBR2hsR1AwUVNVa0piXG51TDYydFcybGtRS0JnRE1RVUMwZHg0eEpmQUI4QTZGOXl1cWg2MU9zdXpRQlhaSC81dW4vUkN4VkM1eHZkdkxPXG5XWGFYT1J6eXNZejl2bzFaT1ZhbXRUU0swMHUzeHRIZVI0cDNDSy9ndk9kTEdMczRHSS9XQW1aZ2J5V01BN25oXG5Uc1pvRjdMaHVsU1BRSXl3bjlIYnhCZGw1Z1RLbGZCMm4rTHVYdWxVMEtaUitMOGZpaml4QTlycEFvR0JBSjZzXG5SRUMxelI1dXkxdDVncVBjdzNvTzZKdXNMeGdJUFZ3UDEvQVBDVEhyRjdJNTNGTWtNZUZ6TVM2Z25QaWl0VEdWXG5lUVpNYjFvL0NndkNybU9lM04zTCtFNnNKeTBEaXpSRC9MMzVuTmJHK1FtS21kdVhrZVlkUm9rYTNBZytuM0pOXG5QbWErTlJiMzc3M0RKdzAzS1N4ZC9IZTh0Rm1YTXlwTXZkM2hyTVdSQW9HQVllVXdTR3BPcFFMS0pVK3U4YlBlXG5RTWRwT3JQZmNDSlVSL0ptSHViQ0FZb21qMjQ5U0lqSUk0QisyWWdRN1RpcEI4eThtN0RSdVdpSE90MFVpbmdoXG5lQ2NwUmRsTU5DenNhc0JUOGtteW5LN3FlTUZGTmtoeUVQaTA0UDV5bVVCRjV0TVMrRE8wbldSVFRqSzhDaVBIXG53SHR4SDFyZlhJSjd0Y3FxY25HV1dhcz1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsImNsaWVudF9lbWFpbCI6ImRlZnQtZWZmZWN0LTMxNzYwOUBhcHBzcG90LmdzZXJ2aWNlYWNjb3VudC5jb20iLCJjbGllbnRfaWQiOiIxMTA2OTA0NjI5ODI0MjE0Mjc2OTMiLCJhdXRoX3VyaSI6Imh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwidG9rZW5fdXJpIjoiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLCJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLCJjbGllbnRfeDUwOV9jZXJ0X3VybCI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZGVmdC1lZmZlY3QtMzE3NjA5JTQwYXBwc3BvdC5nc2VydmljZWFjY291bnQuY29tIn0
          name: cf-java-gha-test-1
          env_vars: PROJECT_ID=deft-effect-317609
          runtime: java11
          region: us-central1
          entry_point: com.example.Example
          # Specifies which action should trigger the function.
          event_trigger_type: google.storage.object.finalize
          # Specifies which resource from eventTrigger is observed.
          event_trigger_resource: projects/_/buckets/csv-input-22062021
          serviceAccountEmail: deft-effect-317609@appspot.gserviceaccount.com
